# Generated by Django 4.2 on 2023-04-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_article_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
