# Generated by Django 4.2 on 2023-04-06 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_remove_article_date_time_article_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
    ]
