# Generated by Django 4.2 on 2023-04-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_remove_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
